// FROZEN (Phase 0). Maps every SourceId to its parser. Parser agents fill in the
// stub bodies in src/content/sites/*; they do NOT edit this file.
import type { Parser, SourceId } from "@optionpilot/contracts";
import { parseYahooOptions, parseYahooVix } from "./sites/yahooOptions";
import { parseOptioncharts } from "./sites/optioncharts";
import { parseYahooAnalysis } from "./sites/yahooAnalysis";
import { parseFinviz, parseFinvizSpy } from "./sites/finviz";
import { parseFredT10Y2Y, parseFredHyOas } from "./sites/fred";
import { parseStockoracle } from "./sites/stockoracle";

export const REGISTRY: Record<SourceId, Parser> = {
  yahoo_options: parseYahooOptions,
  optioncharts: parseOptioncharts,
  yahoo_analysis: parseYahooAnalysis,
  finviz: parseFinviz,
  stockoracle: parseStockoracle,
  fred_t10y2y: parseFredT10Y2Y,
  fred_hyoas: parseFredHyOas,
  yahoo_vix: parseYahooVix,
  finviz_spy: parseFinvizSpy,
};

export function getParser(source: SourceId): Parser {
  return REGISTRY[source];
}
